name: Update Badges

on:
  schedule:
    # Runs daily at 2 AM UTC
    - cron: "0 2 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  update-badges:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Badges
        uses: hairbui76/credly-badges@v1.2.1
        with:
          CREDLY_USER: ${{ github.actor }}
          GIT_COMMIT_MESSAGE: ":memo: chore(readme) Update badges"
